### ISSUE TITLE
App returns to the previous screen to request code again when you change context to another app

### ISSUE THREAD

**Issue by tiagodavi** [liveviewnative/narwin_chat#19] opened 2022-08-27 00:32 UTC
Once I open the app it asks my email, then I type my email and it asks for a login code, at that moment if I change context to copy the login code from my email app it returns to the previous screen by asking for my email again, if I type  it sends me a new login code and the previous code stops working.... in summary it's impossible to change context because the app refreshes and returns to the login page.

**Comment by tiagodavi** [comment] 2022-08-27 00:33
![Screen Shot 2022-08-26 at 21 32 58](https://user-images.githubusercontent.com/1058350/187007106-ec12b95f-2800-4a6f-a765-85d03dde8fb7.png)

**Comment by Serabe** [comment] 2022-08-28 12:35
Having the same problem. Unable to login from my cellphone alone.

**Comment by Serabe** [comment] 2022-08-28 12:36
This is a duplicate of #13

**Closed** 2022-08-28 16:26 UTC
